# Membuat object Statefulset dengan Nama mongodb beserta identitas label
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: karsajobs
    tier: database

# Bagian konfigruasi untuk spec StatefulSet
spec:
  # Sabagai penghubung selector yang terdapat di object Service
  # Menggunakan penghubung selector "app: karsajobs" dan "tier: database"
  selector:
    matchLabels:
      app: karsajobs
      tier: database
  # Menggunakan service name "mongodb" dan mereplikasi pod sebanyak 1 unit
  # Memiliki waktu tunggu minimal 10s
  serviceName: mongodb
  replicas: 1
  minReadySeconds: 10

  # Merupakan konfigurasi pod mulai dari pemberian label dan spesifikasi container yang akan digunakan
  template:
    metadata:
      labels:
        app: karsajobs
        tier: database
    # Spesifikasi container menggunakan image mongodb dengan versi terbaru dan mengexpose port 27017
    # Menambahkan konfigurasi environment database dan applikasi yang berjalan nantinya 
    # Menambahkan konfigurasi untuk mount volume pada container   
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
          name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        - name: mongo-config
          mountPath: /config
          readOnly: true
        - name: mongo-secret
          mountPath: /etc/mongo-credentials
          readOnly: true

      # Pemetaan konfigurasi volume yang digunakan oleh pod
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
      - name: mongo-config
        configMap:
          name: mongo-configmap
          items:
            - key: mongo.conf
              path: mongo.conf
      - name: mongo-secret
        secret:
          secretName: mongo-secret