# Menggunakan Docker Compose Versi 3.7"
version: "3.7"

# Deklarasi service item-db dan item-app
services:

  item-db:
    # Menggunakan image MongoDB versi 3
    image: mongo:3
    # Mount volume app-db:/data/db
    volumes:
      - app-db:/data/db
    # Menerapkan restart policy agar selalu restart jika terhenti
    restart: always
    # Mendefiniskan port MongoDB
    ports:
      - 27017:27017

  item-app:
    # Menerapkan restart policy agar selalu restart jika terhenti
    restart: always
    # Mengambil image di Github Packages yang telah diunggah sebelumnya
    image: "ghcr.io/dimaskhosyi/todo-app:v1"
    # Mapping port 8080 ke 80
    ports:
      - 80:8080
    # Membuat service item-app berjalan setelah item-db
    depends_on:
      - item-db
    environment:
      WAIT_HOSTS: item-db:27017

# Mendefinisikan volumes app-db
volumes:
  app-db: